---
title: "Migración de retorno 2015"
author: "Indicadores sociodemográficos"
output:
   html_document:
      highlight: tango
      theme: flatly
      toc: yes
      toc_depth: 2
      toc_float:
        collapsed: yes
---

\usepackage{color}

```{=html}
<style>
code.r{
  font-size: 10px;
}
pre {
  font-size: 12px
}
</style>

<style>
body {
text-align: justify;
font-style: normal;
font-family: "Montserrat";
font-size: 12px
}
h1.title {
  font-size: 40px;
  color: #000D3B;
}
h1 {
  color: #B6854D;
}
h2 {
  color: #172984;
}
h3 {
  color: #172984;
}
</style>
```

```{=html}
<style>
.nav>li>a {
    position: relative;
    display: block;
    padding: 10px 15px;
    color: #0A2687;
}
.nav-pills>li.active>a, .nav-pills>li.active>a:hover, .nav-pills>li.active>a:focus {
    color: #ffffff;
    background-color: #09C2BC;
}
</style>
```

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, cache = FALSE, cache.lazy = FALSE, 
                         eval = FALSE, class.source = "fold-show")
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
options(digits = 2, encoding = "UTF8")
```   
 

```{r, echo=FALSE}
rm(list = ls())
```

```{r, echo=FALSE}
setwd(here::here())
```


```{r, echo=FALSE}
#Font Stlye
require(showtext)
library(extrafont)
# activar showtext
showtext_auto()
#font_add_google("Montserrat", "montserrat")
#font_add_google("Raleway", "Raleway")
loadfonts(device = "win")
font.add("montserrat", regular = 'C:/Users/dvill/AppData/Local/Microsoft/Windows/Fonts/Montserrat-Light.ttf')
```



```{r, echo = FALSE}
# Librerías que se usaron en el documCVE_ENTo
require(chorddiag)
require(circlize)
require(haven)
require(Hmisc) # %nin%
require(dplyr)
require(survey)
require(srvyr)
require(stringr)
require(sna)
require(expss)
require(knitr)
require(kableExtra)
require(sjlabelled)
require(gt)
require(ggplot2)
require(ggpubr)
require(ggalluvial)
require(ggsankey)
require(ggrepel)
require(tibble)
require(tidyr)
require(reshape2)
require(openxlsx)
```
